input: '/media/vutrungnghia/New Volume/P2-ImageMatchingChallenge/dataset/challenge-dataset/valid'
output: /media/vutrungnghia/New Volume/P2-ImageMatchingChallenge/dataset/challenge-data-brown-data-compress/32

# input: "/mnt/DATA/Phototourism-dataset/train" 
# output: "/mnt/DATA/patch_datasets/challenge3"

test_size: 50000 # pos = neg = test_size, do not change
batch_size: 10000 # use to generate test set, 
                  # in case number of 3dpoints < 10000, set batch_size = n_3dpoints
