dataset:
    challenge_root: challenge-data
    brown_root: brown-data
    
    train_mean_image: 0.443728476019 # liberty
    train_std_image: 0.20197947209
    train_scenes: ['brandenburg_gate', 'notre_dame_front_facade', 'pantheon_exterior', 'buckingham_palace']
    
    test_scenes:
        challenge: ['reichstag', 'st_peters_square', 'sacre_coeur']
        brown: ['liberty', 'notredame', 'yosemite']

model_dir: models
experiment_name: train_on_challenge_data

loss: triplet_margin
batch_reduce: min
num_workers: 8
anchorave: False
resume: '' #checkpoint_20-03-29_13:33:05_1.pth
start_epoch: 0
epochs: 20
anchorswap: True
batch_size: 1024
test_batch_size: 1024
n_triplets: 5000000
margin: 1.0
learning_rate: 10.0
fliprot: False
augmentation: False
lr_decay: 0.000001
weight_decay: 0.0001

environment:
    use_cuda: True
    gpu_id: 3
    seed: 0
