dataset:
    challenge_root: /home/nghiavt/workspace/dataset/32
    brown_root: /home/nghiavt/workspace/brown-data
    
    mean: 0.443728476019 # mean on train patch
    std: 0.20197947209 # std on train patch
    train_scenes: [
        'brandenburg_gate',
       'buckingham_palace',
       'colosseum_exterior',
       'grand_place_brussels',
       'hagia_sophia_interior',
       'notre_dame_front_facade',
       'palace_of_westminster',
       'pantheon_exterior',
       'prague_old_town_square',
       'taj_mahal',
       'temple_nara_japan',
       'trevi_fountain',
        'westminster_abbey']
    test_scenes:
        challenge: ['sacre_coeur', 'st_peters_square', 'reichstag']
#         brown: ['notredame', 'yosemite', 'liberty']

model_dir: models/train_on_challenge_data

loss: triplet_margin
batch_reduce: min
n_workers: 0
anchorave: False
resume: models/train_on_challenge_data/checkpoint_20-04-15_19:57:46_1.pth
start_epoch: 0
epochs: 20
anchorswap: True
batch_size: 1024
test_batch_size: 1024
margin: 1.0
lr: 0.001
fliprot: False
augmentation: False
lr_decay: 0.000001
weight_decay: 0.0001

use_cuda: False
gpu_id: 0
