images: /media/vutrungnghia/New Volume/P2-ImageMatchingChallenge/dataset/evaluation/images
kps: /media/vutrungnghia/New Volume/P2-ImageMatchingChallenge/dataset/evaluation/hieu
output: /media/vutrungnghia/New Volume/P2-ImageMatchingChallenge/dataset/evaluation/hieu-64-gray

size: 64
rgb: False
