python plot_histogram_iou.py --scene reichstag --input /home/hieu123/data/local_features
python plot_histogram_iou.py --scene brandenburg_gate --input /home/hieu123/data/local_features
python plot_histogram_iou.py --scene buckingham_palace --input /home/hieu123/data/local_features
python plot_histogram_iou.py --scene colosseum_exterior --input /home/hieu123/data/local_features
python plot_histogram_iou.py --scene grand_place_brussels --input /home/hieu123/data/local_features
python plot_histogram_iou.py --scene hagia_sophia_interior --input /home/hieu123/data/local_features
python plot_histogram_iou.py --scene notre_dame_front_facade --input /home/hieu123/data/local_features
python plot_histogram_iou.py --scene palace_of_westminster --input /home/hieu123/data/local_features
python plot_histogram_iou.py --scene pantheon_exterior --input /home/hieu123/data/local_features
python plot_histogram_iou.py --scene prague_old_town_square --input /home/hieu123/data/local_features
python plot_histogram_iou.py --scene sacre_coeur --input /home/hieu123/data/local_features
python plot_histogram_iou.py --scene st_peters_square --input /home/hieu123/data/local_features
python plot_histogram_iou.py --scene taj_mahal --input /home/hieu123/data/local_features
python plot_histogram_iou.py --scene trevi_fountain --input /home/hieu123/data/local_features
python plot_histogram_iou.py --scene westminster_abbey --input /home/hieu123/data/local_features
python plot_histogram_iou.py --scene temple_nara_japan --input /home/hieu123/data/local_features
